### ISSUE TITLE
 Sending and receiving variables from Simulink to Arduino

### ISSUE THREAD

**Issue by Desoky01** [leomariga/Simulink-Arduino-Serial#1]
Dear Leonardo Mariga;
could you please help me solve this problem?

I want to send variables from Simulink to Arduino (for example 7 variables) each variable has a value varying from [0 to 255]
Then, send these variables from Arduino to Simulink.

https://drive.google.com/drive/folders/1G1Gq4NzOqOURmDxV1TbSAQAeoBhJWKgF?usp=sharing

Thank you for your support.

**Comment by leomariga** [comment]
Can you elaborate exactly what is your problem?
